# Generated by Django 3.2.5 on 2021-07-24 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='持ち主名')),
                ('number', models.CharField(max_length=100, verbose_name='学籍番号')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='コメント')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名')),
                ('founder', models.CharField(max_length=100, verbose_name='発見者名')),
                ('left_or_unknown', models.IntegerField(choices=[(1, '忘れ物'), (2, '放置物品')], default=1, null=True)),
                ('photo', models.ImageField(upload_to='images/', verbose_name='写真')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='発見日')),
                ('deadline', models.DateField(default=datetime.date(2021, 8, 8), max_length=100, verbose_name='期日')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='コメント')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='listitems.owner', verbose_name='持ち主')),
            ],
        ),
    ]
