# Generated by Django 3.2.5 on 2021-12-29 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listitems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 1, 12), max_length=100, verbose_name='期日'),
        ),
    ]
